config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'pages#index'

  resources :category
  resources :article
  resources :tags
  resources :search

  namespace :api do
    resources :service do
      collection do
        post 'upload'
      end
    end
  end

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title BKT Viet Nam
    / link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600&subset=latin,vietnamese,latin-ext' rel='stylesheet' type='text/css'
    meta http-equiv="Content-Type" content="text/html; charset=UTF-8"
    meta name="google-site-verification" content="6zgDGjPhoFXGwnv7xcA_ER2opEo9PsKOm4pfyIJEx7A"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      header.clearfix
        .col-md-8
          .logo.pull-left
            = link_to image_tag('BKT-logo.jpg'), root_path
          .slogan.pull-left
            span = Setting.get_value :slogan
        .col-md-4
          .links.pull-right
            = link_to image_tag('usa-flag.png'), "http://www.bkt21.com"
            = link_to image_tag('south-korea-flag.png'), "http://www.bkt21.co.kr/"
          .search-bar.pull-right
            .input-group
              input type="text" class="form-control input-keyword" placeholder="Search..."
                span.input-group-btn
                  button.btn.btn-primary.btn-search type="button" Search
      - if @slides.present?
        #slider.nivoSlider
          - @slides.each do |slide|
            - if slide.url.present?
              = link_to image_tag(slide.image.url), slide.url
            - else
              = image_tag(slide.image.url)
      #main-content.row
        .col-md-3#sidebar
          .sidebar-box.contact-box
            .sidebar-title Liên hệ
            .sidebar-content
              table.table
                tr
                  td Email
                  td = Setting.get_value :email
                tr
                  td Phone
                  td = Setting.get_value :phone
                tr
                  td Hotline
                  td = Setting.get_value :hotline
                tr
                  td Views
                  td = View.count
                  
          .sidebar-box.news-box
            .sidebar-title Tin tức
            .sidebar-content
              - @latest_articles.each do |article|
                .media
                  .media-left
                    = link_to image_tag(article.image.url(:thumb)), article_path(article.slug)
                  .media-body
                    h4.media-heading = link_to article.title, article_path(article.slug)
                    p = article.description[0..150]
        .col-md-9#content
          ul.nav.nav-pills.main-nav
            - @menus.each do |menu|
              li role="presentation" class="dropdown"
                a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  span = menu.title
                  span class="caret"
                ul class="dropdown-menu"
                  - menu.children.each do |category|
                    li
                      - if category.articles.count == 1
                        a href="#{article_path(category.articles.first.slug)}" = category.title
                      - else
                        a href="#{category_path(category.slug)}" = category.title
          = yield
      footer.row
        .copyright
          .col-md-6
            span Copyright ©2015. All Rights Reserved. BKTVN.COM
          .col-md-6.aligned-right
            span BKT Vietnam Co, Ltd
        .col-md-2
          = image_tag('BKT-logo.jpg')
        .col-md-8
          h4 BKT Vietnam Co, Ltd
          .row
            .col-md-9
              table.table
                tr
                  td Address:
                  td = Setting.get_value :address
                tr
                  td Email:
                  td = Setting.get_value :email
                tr
                  td Fax:
                  td = Setting.get_value :fax
                tr
                  td Hotline:
                  td = Setting.get_value :hotline
            .col-md-3
              table.table
                tr
                  td Mã số thuế:
                  td 0106569734
                tr
                  td GPĐKKD:
                  td 011043002318
                tr
                  td Website:
                tr
                  td
                    a href="http://bktvn.com" http://bktvn.com<br>
                    a href="http://bkt21.com" http://bkt21.com<br>
                    a href="http://bkt21.co.kr" http://bkt21.co.kr<br>